Ankh-Morpork MVC/Models/Assassin.cs
namespace Ankh_Morpork_MVC.Models
{
    public class Assassin : Character
    {
        public double? MaxReward { get; set; }
        public double? MinReward { get; set; }
        public bool? IsBusy { get; set; }
        public string OfferMessage { get; set; }
    }
}

Ankh-Morpork MVC/Controllers/AssassinsController.cs
using Ankh_Morpork_MVC.Repositories;
using System.Web.Mvc;

namespace Ankh_Morpork_MVC.Controllers
{
    public class AssassinsController : Controller
    {
        private IAssassinRepository _repository;
        public AssassinsController(IAssassinRepository repository)
        {
            _repository = repository;

        }

        [Route("Assassins/Accept/{reward}/{hood}")]
        public ActionResult Accept(double reward, bool hood)
        {
            _repository.AddReward(reward, hood);
            _repository.RandomizeBusiness();
            if (!_repository.ProcessResponce(accept: true))
                return Deny();
            return RedirectToAction("CreateEvent", "Events");
        }
        public ActionResult Deny()
        {
            return RedirectToAction("GameOver", "Home");
        }
    }
}

Ankh-Morpork MVC/Views/Assassins/NewAssassin.cshtml
@model Ankh_Morpork_MVC.Dtos.EventDto
@using Ankh_Morpork_MVC.Models
@{
    var character = (Assassin)Model.Character;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Accept", "Assassins", new { reward = 0, hood = false }))
{
    <div class="container">
        <div class=" flip-card effect-on-active flip-vertical" id="flip-card">
            <div class="front">
                <div class="card play-card assassin-guild">
                    <img class="card-img-top character-image" src="~/Source/Assassins/assassin.jpg">
                    <div class="card-body">
                        <div class="guild-logo" id="assassin-logo">
                            <img src="~/Source/Assassins/logo.png" />
                        </div>
                        <div class="deal">
                            <p id="show-reward"></p>
                        </div>
                        <a onclick="FlipCard()" class="information-top">
                            <img src="~/Source/info.png" />
                        </a>
                        <h3 class="character-name">@character.Name</h3>
                        <h5 class="guild">Assassins' Guild</h5>
                        <p class="card-text offer-message">@character.OfferMessage</p>
                        @Html.TextBoxFor(m => m.Reward, null, new { type = "range", min = "0", max = Model.PlayerMoney, step = "0.01", id = "reward-bar" });
                        <p class="card-text meet-message">@character.MeetMessage</p>
                    </div>
                </div>
            </div>
            <div class="back">
                <div class="card play-card assassin-guild">
                    <div class="card-body">
                        <div class="guild-image" id="assassin-logo">
                            <img src="~/Source/Assassins/logo.png" />
                        </div>
                        <a onclick="FlipCard()" class="information-bottom">
                            <img src="~/Source/info.png" />
                        </a>
                        <h3 class="character-name">Assassins' Guild</h3>
                        <p class="card-text meet-message">@character.GuildData</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container inventory-container">
            <img class="inventory" src="../Source/Inventory.png" />
            <div class="row">
                <div class="col-3">
                    <a class="deny-button" href="@Url.Action("Deny", "Assassins", null)">
                        <img src="~/Source/close.png" />
                    </a>
                </div>
                <div class="col-2">
                    <div class="count">
                        <img src="~/Source/coins.png" />
                        <p class="coins">@Model.PlayerMoney</p>
                    </div>
                </div>
                <div class="col-2">
                    <div class="count">
                        <img src="~/Source/beer.png" />
                        <p class="beer">@Model.PlayerBeer</p>
                    </div>
                </div>

                <div class="col-2">
                    @{
                        if (Model.PlayerHood > 0)
                        {
                            <a href="@Url.Action("Accept", "Assassins")/0/true">
                                <div class="hood-button-active">

                                    <img src="~/Source/hood.png" />
                                </div>
                            </a>
                        }
                        else
                        {
                            <div class="hood-button-disabled">
                                <img src="~/Source/hood-bw.png" />
                            </div>
                        }
                    }
                </div>
                <div class="col-3">
                    <button class="accept-button" type="submit">
                        <img src="~/Source/check.png" />
                    </button>
                </div>
            </div>
        </div>

    </div>
}



@section Scripts{
    <script>
        var slider = document.getElementById("reward-bar");
        var output = document.getElementById("show-reward");
        output.innerHTML = slider.value;
        slider.oninput = function () {
            output.innerHTML = this.value;
        }
        function FlipCard() {
            var element = document.getElementById("flip-card");
            if (element.classList.contains("active") === true)
                element.classList.remove("active");
            else
                element.classList.add("active");

        }
    </script>
}