Ankh-Morpork MVC/Models/Thieve.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ankh_Morpork_MVC.Models
{
    public class Thieve : Character
    {
        public double Fee { get; set; }

    }
}

Ankh-Morpork MVC/Controllers/ThievesController.cs
using Ankh_Morpork_MVC.Repositories;
using System.Web.Mvc;

namespace Ankh_Morpork_MVC.Controllers
{
    public class ThievesController : Controller
    {
        private IThiefRepository _repository;
        public ThievesController(IThiefRepository repository)
        {
            _repository = repository;
        }
        [HttpPost]
        [Route("Thieves/Accept/{fee}")]
        public ActionResult Accept(double fee)
        {
            _repository.AddFee(fee);
            if (!_repository.ProcessResponce(accept: true))
                return Deny();
            return RedirectToAction("CreateEvent", "Events");
        }
        public ActionResult Deny()
        {
            return RedirectToAction("GameOver", "Home");
        }
    }
}

Ankh-Morpork MVC/Views/Thieves/NewThieve.cshtml
@model Ankh_Morpork_MVC.Dtos.EventDto
@using Ankh_Morpork_MVC.Models
@{
    var character = (Thief)Model.Character;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Accept", "Thieves", new { fee = character.Fee }))
{
    <div class="container">
        <div class=" flip-card effect-on-active flip-vertical" id="flip-card">
            <div class="front">
                <div class="card play-card thief-guild">
                    <img class="card-img-top character-image" src="~/Source/Thieves/thief.png">
                    <div class="card-body">
                        <div class="guild-logo" id="thief-logo">
                            <img src="~/Source/Thieves/logo.png" />
                        </div>
                        <div class="deal">
                            <p>@character.Fee</p>
                        </div>
                        <a onclick="FlipCard()" class="information-top">
                            <img src="~/Source/info.png" />
                        </a>
                        <h3 class="character-name">@character.Name</h3>
                        <h5 class="guild">Thieves' Guild</h5>
                        <p class="card-text meet-message">@character.MeetMessage</p>
                    </div>
                </div>
            </div>
            <div class="back">
                <div class="card play-card thief-guild">
                    <div class="card-body">
                        <div class="guild-image" id="thief-logo">
                            <img src="~/Source/Thieves/logo.png" />
                        </div>
                        <a onclick="FlipCard()" class="information-bottom">
                            <img src="~/Source/info.png" />
                        </a>
                        <h3 class="character-name">Thieves' Guild</h3>
                        <p class="card-text meet-message">@character.GuildData</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container inventory-container">
            <img class="inventory" src="../Source/Inventory.png" />
            <div class="row">
                <div class="col-3">
                    <a class="deny-button" href="@Url.Action("Deny", "Thieves", null)">
                        <img src="~/Source/close.png" />
                    </a>
                </div>
                <div class="col-2">
                    <div class="count">
                        <img src="~/Source/coins.png" />
                        <p class="coins">@Model.PlayerMoney</p>
                    </div>
                </div>
                <div class="col-2">
                    <div class="count">
                        <img src="~/Source/beer.png" />
                        <p class="beer">@Model.PlayerBeer</p>
                    </div>
                </div>

                <div class="col-2">
                    @{
                        if (Model.PlayerHood > 0)
                        {
                            <div class="hood-button-active">

                                <img src="~/Source/hood.png" />
                            </div>
                        }
                        else
                        {
                            <div class="hood-button-disabled">
                                <img src="~/Source/hood-bw.png" />
                            </div>
                        }
                    }
                </div>
                <div class="col-3">
                    <button class="accept-button" type="submit">
                        <img src="~/Source/check.png" />
                    </button>
                </div>
            </div>
        </div>

    </div>
}



@section Scripts{
    <script>
        function FlipCard() {
            var element = document.getElementById("flip-card");
            if (element.classList.contains("active") === true)
                element.classList.remove("active");
            else
                element.classList.add("active");

        }
    </script>
}